Repository codeRIT/hackathon-manager, pull requests merged in 2020-12, with the labels that each got.

#409 feat(settings): Simplifies Config
  app/controllers/manage/configs_controller.rb
  app/views/manage/configs/index.html.haml
Labels: 2.1

#395 feat: Adds support for digital-only hackathons
  app/views/application/_questionnaire_summary.html.haml
  app/views/layouts/manage/application.html.haml
  app/views/manage/dashboard/index.html.haml
  app/views/manage/questionnaires/_form.html.haml
  app/views/manage/questionnaires/_overview.html.haml
  app/views/manage/stats/index.html.haml
  app/views/questionnaires/_form.html.haml
  app/views/rsvps/show.html.haml
  config/app.yml
  config/locales/en.yml
Labels: 2.1

#429 feat: Adds Legal Agreements object for dynamic agreements
  .gitignore
  app/assets/stylesheets/forms/_forms.sass
  app/controllers/manage/agreements_controller.rb
  app/controllers/manage/checkins_controller.rb
  app/controllers/manage/questionnaires_controller.rb
  app/controllers/questionnaires_controller.rb
  app/controllers/rsvps_controller.rb
  app/models/agreement.rb
  app/models/questionnaire.rb
  app/views/application/_unaccepted_agreements_notice.html.haml
  app/views/doorkeeper/applications/index.html.haml
  app/views/layouts/manage/application.html.haml
  app/views/manage/agreements/_form.html.haml
  app/views/manage/agreements/edit.html.haml
  app/views/manage/agreements/index.html.haml
  app/views/manage/agreements/new.html.haml
  app/views/manage/questionnaires/_checkin_compliance_card.html.haml
  app/views/manage/questionnaires/_form.html.haml
  app/views/questionnaires/_form.html.haml
  app/views/questionnaires/show.html.haml
  app/views/rsvps/show.html.haml
  config/locales/en.yml
  config/routes.rb
  db/migrate/20201130220942_create_agreements.rb
  db/migrate/20201130221702_create_agreements_questionnaires_join.rb
  db/migrate/20201209053827_remove_old_agreement_data_from_questionnaire.rb
  db/schema.rb
  test/controllers/bus_lists_controller_test.rb
  test/controllers/manage/agreements_controller_test.rb
  test/controllers/manage/bus_lists_controller_test.rb
  test/controllers/manage/dashboard_controller_test.rb
  test/controllers/manage/questionnaires_controller_test.rb
  test/controllers/manage/schools_controller_test.rb
  test/controllers/manage/stats_controller_test.rb
  test/controllers/questionnaires_controller_test.rb
  test/controllers/rsvps_controller_test.rb
  test/factories/agreement.rb
  test/factories/questionnaire.rb
  test/jobs/bulk_message_job_test.rb
  test/models/agreement_test.rb
  test/models/bus_list_test.rb
  test/models/questionnaire_test.rb
  test/models/user_test.rb
Labels: 2.1

#417 refactor: Changes hackathon_manager to HackathonManager
  app/views/layouts/manage/application.html.haml
  db/message-template-default.html.mustache
Labels: 2.1

#415 feat: Adds GitLab VCS URL support
  app/models/questionnaire.rb
  app/views/application/_questionnaire_summary.html.haml
  app/views/manage/questionnaires/_form.html.haml
  app/views/manage/questionnaires/_overview.html.haml
  app/views/questionnaires/_form.html.haml
  test/models/questionnaire_test.rb
Labels: 2.1

#421 fix: Fixes pluralization of "Callback URL"
  config/locales/doorkeeper.en.yml
Labels: 2.1

#440 refactor: Removes legal section from config
  app/controllers/manage/configs_controller.rb
  app/views/manage/configs/index.html.haml
  config/app.yml
  config/locales/en.yml
Labels: 2.1

#428 fix(map): changed map overflow from scroll to auto
  app/assets/stylesheets/manage.sass
Labels: 2.1

#443 fix(questionnaire): missing information now in correct place
  app/assets/javascripts/validate.js
  app/views/questionnaires/_form.html.haml
Labels: 2.1.1

#451 Fix agreement label break line bug on mobile
  app/models/agreement.rb
Labels: unplanned

#446 feat: Removes semantic-release
  .github/workflows/release.yml
  package.json
  yarn.lock
Labels: 2.1.1

#449 refactor: Moves CI to develop branch
  .github/workflows/build.yml
Labels: 2.1.1

#452 master <- 2.1.1
  .github/workflows/build.yml
  .github/workflows/release.yml
  app/assets/javascripts/validate.js
  app/models/agreement.rb
  app/views/questionnaires/_form.html.haml
  package.json
  yarn.lock
Labels: 2.1.1

#471 fix: Shows questionnaires_closed_message on registration
  app/views/devise/registrations/new.html.haml
Labels: 2.1.2

#465 feat: Allows agreements to be fully customizable
  app/assets/javascripts/validate.js
  app/controllers/manage/agreements_controller.rb
  app/models/agreement.rb
  app/views/manage/agreements/_form.html.haml
  app/views/manage/agreements/index.html.haml
  config/locales/en.yml
  db/migrate/20201218010133_convert_agreements_to_text.rb
  db/schema.rb
  test/controllers/manage/agreements_controller_test.rb
  test/factories/agreement.rb
  test/models/agreement_test.rb
Labels: 2.1.2

#467 fix(hakiri): fixed un-escaped regex for vcs link
  app/models/questionnaire.rb
Labels: 2.1.2

#472 master <- develop (2.1.2)
  app/assets/javascripts/validate.js
  app/controllers/manage/agreements_controller.rb
  app/models/agreement.rb
  app/models/questionnaire.rb
  app/views/devise/registrations/new.html.haml
  app/views/doorkeeper/authorizations/error.html.haml
  app/views/manage/agreements/_form.html.haml
  app/views/manage/agreements/index.html.haml
  config/locales/en.yml
  db/migrate/20201218010133_convert_agreements_to_text.rb
  db/schema.rb
  test/controllers/manage/agreements_controller_test.rb
  test/factories/agreement.rb
  test/models/agreement_test.rb
Labels: 2.1.2

#484 fix: Uninstalls deprecated chromedriver
  Gemfile
  Gemfile.lock
  vendor/cache/archive-zip-0.12.0.gem
  vendor/cache/chromedriver-helper-2.1.1.gem
  vendor/cache/io-like-0.3.1.gem
Labels: 2.2

#485 fix: VCS regex matches all valid usernames for each provider; URLs are now case-insensitive, dokku check extended
  CHECKS
  app/models/questionnaire.rb
  test/models/questionnaire_test.rb
Labels: 2.1.3
