Repository codeRIT/hackathon-manager, pull requests merged in 2021-07, with the labels that each got.

#722 refactor(User): Converts user to API only
  app/controllers/users_controller.rb
  app/views/users/show.json.jbuilder
Labels: 3.0.0

#726 ci: Configure HoundCI to follow our SCSS style rules
  .hound.yml
  .sass-lint.yml
Labels: 3.0.0

#727 feat(questionnaire): those 13 and under can't make questionnaires
  app/models/questionnaire.rb
  test/models/questionnaire_test.rb
Labels: 3.0.0, backend

#725 feat: Scaffolded frontend projects and started work on wireframe implementations
  .hound.yml
  .sass-lint.yml
  frontend/App.vue
  frontend/assets/scss/style.scss
  frontend/index.js
  frontend/package.json
  frontend/routes/Profile.vue
  frontend/routes/manage/Dashboard.vue
Labels: 3.0.0, frontend

#732 ci: Configure HoundCI to allow mulitple SCSS selectors on one line
  .sass-lint.yml
Labels: 3.0.0

#733 refactor(RSVP): Converts RSVP controller to API only
  app/controllers/rsvps_controller.rb
  app/views/rsvps/show.html.haml
  config/routes.rb
  test/controllers/rsvps_controller_test.rb
Labels: 3.0.0, backend
