Repository codeRIT/hackathon-manager, pull requests merged in 2021-06, with the labels that each got.

#680 refactor(Questionnaire): Converts public questionnaire to API only
  Gemfile
  Gemfile.lock
  app/controllers/questionnaires_controller.rb
  app/views/questionnaires/_form.html.haml
  app/views/questionnaires/edit.html.erb
  app/views/questionnaires/new.html.haml
  app/views/questionnaires/show.html.erb
  app/views/questionnaires/show.json.jbuilder
  config/routes.rb
  test/controllers/questionnaires_controller_test.rb
  test/integration/oauth_test.rb
  test/integration/user_flows_test.rb
  vendor/cache/jbuilder-2.11.2.gem
Labels: back-end, v3.0.0

#695 ci: Swap HoundCI to use ESLint instead of JSHint
  .eslintrc
  .hound.yml
Labels: frontend, v3.0.0

#696 ci: Revert "Swap HoundCI to use ESLint instead of JSHint (#695)"
  .eslintrc
  .hound.yml
Labels: frontend, v3.0.0

#697 ci: Swap HoundCI to use ESLint instead of JSHint
  .eslintrc
  .hound.yml
Labels: v3.0.0

#681 refactor(Bus_Lists): Converts bus lists to API only
  app/controllers/bus_lists_controller.rb
  app/views/bus_lists/show.html.haml
  app/views/bus_lists/show.json.jbuilder
  test/controllers/bus_lists_controller_test.rb
Labels: backend, v3.0.0

#686 refactor(Events): Converts public Events to API only
  app/controllers/events_controller.rb
  app/views/events/index.json.jbuilder
  app/views/events/show.json.jbuilder
  config/routes.rb
  test/controllers/events_controller_test.rb
Labels: backend, v3.0.0

#688 refactor(Dashboard): Removes the Dashboard
  app/assets/javascripts/manage/map.js
  app/controllers/manage/dashboard_controller.rb
  app/views/manage/dashboard/index.html.erb
  app/views/manage/dashboard/map_data.tsv.erb
  app/views/manage/schools/show.html.erb
  config/routes.rb
  test/controllers/manage/dashboard_controller_test.rb
  test/integration/user_flows_test.rb
Labels: backend, v3.0.0

#692 feat: Scaffolds the frontend with Parcel/Vue/Sass
  .gitignore
  frontend/.editorconfig
  frontend/App.vue
  frontend/README.md
  frontend/index.html
  frontend/index.js
  frontend/package-lock.json
  frontend/package.json
  frontend/routes/About.vue
  frontend/routes/Home.vue
Labels: 3.0.0, frontend

#712 feat: Add `eslint-vue` plugin and fix common eslint error
  .eslintrc
  .gitignore
  frontend/package-lock.json
  frontend/package.json
Labels: 3.0.0, blocked
